SELECT *
FROM EMP;

SELECT *
FROM DEPT d ;

SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH EMPNO = (SELECT MGR FROM EMP WHERE EMPNO= '7499')
	CONNECT BY  EMPNO = PRIOR MGR ;

(SELECT MGR FROM EMP WHERE EMPNO= '7839')

SELECT LEVEL DEPTH, MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	WHERE CONNECT_BY_ISLEAF = 1
	START WITH MGR IS NULL
	CONNECT BY PRIOR EMPNO = MGR 
	ORDER BY 1 DESC;
	

SELECT LEVEL, EMPNO, ENAME, CONNECT_BY_ISLEAF "留덉�留� �끂�뱶", 
	CONNECT_BY_ROOT EMPNO "理쒖긽�쐞 �끂�뱶", 
	JOBSYS_CONNECT_BY_PATH(ENAME, '-'),  
	LPAD(' ', 10*(LEVEL-1)) || EMPNO 吏꾪뻾
	FROM EMP e 
	START WITH MGR IS NULL
	CONNECT BY PRIOR EMPNO = MGR
	ORDER BY 1 ;
	
	SELECT JOB, SUM(SAL)
		FROM EMP e 
		WHERE (JOB,SAL) IN (SELECT JOB, SAL 
							FROM EMP e2
							WHERE JOB ='SALESMAN'
							GROUP BY JOB,SAL);
						
		
SELECT JOB , 급여합계 
	FROM (SELECT JOB, SUM(SAL) 급여합계
					FROM EMP e2
					WHERE JOB != 'SALESMAN'
					GROUP BY JOB)
				WHERE 급여합계 > 5000;
			
SELECT d.DNAME , COUNT(EMPNO) 사원수, SUM(SAL)
FROM EMP e,DEPT d 
WHERE e.DEPTNO =d.DEPTNO AND COUNT(EMPNO) >= '3'
GROUP BY DNAME
	
SELECT DNAME ,사원수, SUM(SAL) 
	FROM DEPT d  JOIN (SELECT COUNT(EMPNO) 사원수, SAL
						FROM EMP e
						WHERE COUNT(EMPNO) >= 3)
						ON d.DEPTNO = e.DEPTNO 
						GROUP BY DNAME;
					
					
SELECT DNAME ,COUNT(EMPNO) 사원수, SUM(SAL)
	FROM EMP e JOIN  DEPT d
	ON e.DEPTNO = d.DEPTNO 
	GROUP BY DNAME 
	WHERE COUNT(EMPNO) >= 3;
						
	SELECT * 
		FROM EMP e ;
	
	
	