
DROP TABLE GOODS;
DROP TABLE INVENTORY ;
SELECT * FROM GOODS g ;
SELECT * FROM INVENTORY ;

-- G_CODE와 G-NAME을 복합키 설정
CREATE TABLE GOODS(
    G_CODE CHAR(10) NOT NULL,
    G_NAME VARCHAR(20)NOT NULL,
    PRICE NUMBER(6) NOT NULL,
    CONSTRAINT GOODS_pk PRIMARY KEY(G_CODE, G_NAME)
);




-- G_CODE와 G_NAME을 참조키 설정 
CREATE TABLE INVENTORY(
	G_CODE CHAR(10) PRIMARY KEY,
	G_NAME VARCHAR(20) NOT NULL,
    G_AMOUNT NUMBER(5),   --COLUMN
    M_REGDATE DATE NOT NULL, 
    END_DATE DATE,
    CONSTRAINT INVENTORY_fk FOREIGN KEY(G_CODE, G_NAME) REFERENCES GOODS(G_CODE,G_NAME)
);



INSERT INTO GOODS (G_CODE ,G_NAME , PRICE )VALUES ('ABC1234567',  '새우깡', 10000);
INSERT INTO GOODS (G_CODE ,G_NAME , PRICE )VALUES ('ABC1234568',  '양파링', 20000);
INSERT INTO GOODS (G_CODE ,G_NAME , PRICE )VALUES ('ABC1234569',  '감자깡', 30000);

INSERT INTO INVENTORY (G_CODE, G_NAME, G_AMOUNT ,M_REGDATE , END_DATE)VALUES ('ABC1234567','새우깡', 10, SYSDATE, '20220209');
INSERT INTO INVENTORY (G_CODE, G_NAME, G_AMOUNT ,M_REGDATE , END_DATE)VALUES ('ABC1234568','양파링', 10, SYSDATE, '20220209');

-- INSERT를 넣어주기위해서 관리자는 상품코드와 상품명을 알고있어야 가능하다
-- SELECT로 상품명을 조회해서 상품코드를 얻는 기능을 넣을 것
-- 관리자는 인벤토리에서 수량만 조절가능하게됨

-- 전체조회 , 수량 조절
-- + 단일 조회 / 컬럼 조회
--   INSERT [상품코드] [과자명] 3