SELECT *
FROM EMP;

SELECT *
FROM DEPT d ;

SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH EMPNO = (SELECT MGR FROM EMP WHERE EMPNO= '7499')
	CONNECT BY  EMPNO = PRIOR MGR ;

(SELECT MGR FROM EMP WHERE EMPNO= '7839')

SELECT LEVEL DEPTH, MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	WHERE CONNECT_BY_ISLEAF = 1
	START WITH MGR IS NULL
	CONNECT BY PRIOR EMPNO = MGR 
	ORDER BY 1 DESC;
	

SELECT LEVEL, EMPNO, ENAME, CONNECT_BY_ISLEAF "留덉�留� �끂�뱶", 
	CONNECT_BY_ROOT EMPNO "理쒖긽�쐞 �끂�뱶", 
	JOB SYS_CONNECT_BY_PATH(ENAME, '-'),  
	LPAD(' ', 10*(LEVEL-1)) || EMPNO 吏꾪뻾
	FROM EMP e 
	START WITH MGR IS NULL
	CONNECT BY PRIOR EMPNO = MGR
	ORDER BY 1 ;
	
	SELECT JOB, SUM(SAL)
		FROM EMP e 
		WHERE (JOB,SAL) IN (SELECT JOB, SAL 
							FROM EMP e2
							WHERE JOB ='SALESMAN'
							GROUP BY JOB,SAL);
						
		
SELECT JOB , 급여합계 
	FROM (SELECT JOB, SUM(SAL) 급여합계
					FROM EMP e2
					WHERE JOB != 'SALESMAN'
					GROUP BY JOB)
				WHERE 급여합계 > 5000;
			
SELECT d.DNAME , COUNT(EMPNO) 사원수, SUM(SAL)
FROM EMP e,DEPT d 
WHERE e.DEPTNO =d.DEPTNO AND COUNT(EMPNO) >= '3'
GROUP BY DNAME
	

					
SELECT DNAME ,COUNT(EMPNO) 사원수, SUM(SAL)
	FROM EMP e JOIN DEPT d 
	ON e.DEPTNO = d.DEPTNO 
	GROUP BY DNAME
	HAVING COUNT(EMPNO) >=3; 
	
						
	SELECT * 
		FROM EMP e 
		WHERE JOB='CLERK';
	
SELECT e.JOB, SUM(e3.SAL)
	FROM EMP e , (SELECT EMPNO, SAL
					FROM EMP e2
					WHERE SAL>1000) e3
	WHERE e.EMPNO = e3.EMPNO 
	GROUP BY JOB;

SELECT e.JOB ,SUM(e.SAL)
	FROM (SELECT EMPNO, JOB, SAL
					FROM EMP e2
					WHERE SAL > 1000) e
	WHERE e.EMPNO = e.EMPNO 
	GROUP BY e.JOB;

SELECT e.JOB, SUM(E2)
	FROM (SELECT *
			FROM EMP e
			WHERE SAL > 1000)e2
		GROUP BY e.JOB ;

SELECT JOB ,SUM(SAL)
	FROM EMP e 
	WHERE JOB != (SELECT JOB
					FROM EMP e2
					WHERE SAL < 1000
					GROUP BY JOB)
	GROUP BY JOB;
	
SELECT JOB
	FROM EMP e2
	WHERE SAL > 1000
GROUP BY JOB;

SELECT JOB ,SUM(SAL)
	FROM EMP e 
	WHERE JOB = (SELECT JOB
					FROM EMP e2
					WHERE SAL > 1000
					GROUP BY JOB)
	GROUP BY JOB;

SELECT *
	FROM DEPT d ;

SELECT EMPNO , ENAME , DNAME, LOC
FROM EMP e LEFT JOIN DEPT d 
ON e.DEPTNO =d.DEPTNO
WHERE LOC != 'BOSTON'
AND LOC != 'CHICAGO' 
AND e.DEPTNO = d.DEPTNO OR 
NOT EXISTS (SELECT 1
				FROM DEPT d2
				WHERE d2.DEPTNO = d.DEPTNO) ;

SELECT *
FROM EMP e LEFT JOIN DEPT d 
ON e.DEPTNO =d.DEPTNO;

UPDATE EMP SET DEPTNO = NULL 
WHERE ENAME ='KING' AND 'WARD';

DELETE DEPTNO 
FROM EMP e 
WHERE ENAME ='KING';
			
DELETE DNAME, LOC 
FROM DEPT d, EMP e 
WHERE d.DEPTNO = e.EMPNO 
AND ENAME = 'SMITH'
OR ENAME = 'SCOTT';


SELECT *
	FROM EMP e
	
	
	
SELECT EMP,LEVEL , 
	CONNECT_BY_ISLEAF 마지막노드, 
	CONNECT_BY_ROOT EMP "최상위 사원",
	SYS_CONNECT_BY_PATH(EMP, '->') 전개
	FROM EMPLOYEES e 
	START WITH MGR IS NULL 
	CONNECT BY MGR = PRIOR EMP;
	
