--20220211
--MERGE 하나의 쿼리에 INSERT, UPDATE를 작업할 경우가 있다.
--MERGE 통해서 복잡한 여러개의 쿼리를 하나로 수행할 수 있다.

MERGE
	INTO EMP e
USING DUAL
	ON(e.EMPNO = 6688)
WHEN MATCHED THEN 
	UPDATE 
		SET e.COMM = 9999
	WHEN NOT MATCHED THEN 
		INSERT (e.EMPNO, e.ENAME, e.DEPTNO)
		VALUES('6688','DONGLE', 10);
		
SELECT *
	FROM EMP e
	WHERE EMPNO ='6688';
	
MERGE 
	INTO EMP e
	USING DUAL
		ON (e.EMPNO = 6688)
	WHEN MATCHED THEN 
		UPDATE 
		SET e.DEPTNO =99
		WHERE e.JOB ='SALESMAN'
	DELETE 
		WHERE e.JOB != 'CLERK';
		
	SELECT *
	FROM EMP;