--OUTER JOIN
-- STANDARD JOIN은 INNER JOIN, JOIN ON절 과 같이 사용됨
-- ON -> USING (컬럼명이 같다면...)
-- ON 선행테이블 + 후행테이블
-- USING 조인이 되면 컬럼 단 1회 맨 앞으로 된다.

--NATURAL JOIN 자동으로 같은 컬럼을 찾아서 JOIN을 발생시킨다

--OUTER JOIN : A JOIN B : A선행LEFT, B후행RIGHT

--문제> 스타디움에 등록된 운동장 중에서 홈팀없는 경기장이 있다.
--스타디움과 팀을 조인할때 홈팀이 없는 경기장의 정ㄷ보도 같이 출력해달라

SELECT STADIUM_ID , HOMETEAM_ID 
	FROM STADIUM s LEFT JOIN TEAM t 
	USING (STADIUM_ID)
	ORDER BY 1 ;

SELECT * 
	FROM STADIUM s , TEAM t 
	WHERE s.STADIUM_ID =t.STADIUM_ID (+)
	ORDER BY s.STADIUM_ID ;

SELECT STADIUM_ID , HOMETEAM_ID 
	FROM TEAM t RIGHT JOIN  STADIUM s
	USING (STADIUM_ID)
	ORDER BY 1 ;

SELECT * 
	FROM STADIUM s , TEAM t 
	WHERE s.STADIUM_ID(+) =t.STADIUM_ID
	ORDER BY s.STADIUM_ID ;

SELECT *
	FROM STADIUM s FULL JOIN TEAM t 
	USING (STADIUM_ID);

SELECT *
	FROM DEPT d;

SELECT *
	FROM DEPT_TEMP dt ;

SELECT *
	FROM DEPT d FULL JOIN DEPT_TEMP dt 
	ON d.DNAME = dt.DNAME ;

SELECT *
	FROM DEPT d JOIN DEPT_TEMP dt  -- 이너조인은 중복결과만
	ON d.DNAME = dt.DNAME ;

--LEFT OUTER JOIN은 왼쪽이 다 나옴
SELECT *
	FROM DEPT d LEFT JOIN DEPT_TEMP dt 
	ON d.DNAME = dt.DNAME ;

--RIGHT OUTER JOIN은 오른쪽이 다 나옴
SELECT *
	FROM DEPT d RIGHT JOIN DEPT_TEMP dt 
	ON d.DNAME = dt.DNAME ;

-- FULL OUTER JOIN은 ORACLE LEFT와 RIGHT OUTER JOIN을 동신에 보여줌
SELECT *
	FROM DEPT d FULL JOIN DEPT_TEMP dt 
	ON d.DNAME = dt.DNAME ;















