CREATE TABLE ADMIN(
	SEQ NUMBER PRIMARY KEY,  --COLUMN
	ID VARCHAR2(15) NOT NULL,
	PW VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE SEQ
	START WITH 1
	INCREMENT BY 1;


SELECT *
	FROM ADMIN a ;
	
INSERT INTO ADMIN (SEQ, ID, PW ) VALUES (SEQ.NEXTVAL, 'Goobee', '456');


CREATE TABLE ACCOUNT(
	AC_CODE NUMBER(10) PRIMARY KEY,  --COLUMN
	AC_REGNUM VARCHAR2(10) NOT NULL,
	REGDATE DATE, 
	AC_TEL VARCHAR(20),
	CEO_NAME VARCHAR2(40) NOT NULL
);

DROP TABLE ACCOUNT ;

SELECT *
	FROM ACCOUNT ;

INSERT INTO ACCOUNT VALUES ('002', '1234567890', SYSDATE, '010111111111','한슬기' );

CREATE TABLE INVENTORY(
	G_CODE CHAR(10) PRIMARY KEY,
	G_AMOUNT NUMBER(5),   --COLUMN
	M_REGDATE DATE NOT NULL, 
	END_DATE DATE 
);

SELECT *
	FROM INVENTORY ;

DROP TABLE INVETORY ;

INSERT INTO INVENTORY (G_CODE ,M_REGDATE , END_DATE )VALUES ('ABC1234567',  SYSDATE, '20220209');

CREATE TABLE GOODS(
	G_CODE CHAR(10) PRIMARY KEY,
	G_NAME VARCHAR(20) NOT NULL,  
	PRICE NUMBER(6) NOT NULL
);

DROP TABLE GOODS ;

SELECT *
	FROM GOODS ;

INSERT INTO GOODS (G_CODE ,G_NAME , PRICE )VALUES ('ABC1234567',  '빵', 10000);

--외래키설정
ALTER TABLE INVENTORY 
ADD CONSTRAINTS G_CODE FOREIGN KEY (G_CODE) 
REFERENCES GOODS (G_CODE);