-- 20220120
-- SELECT 는 FROM절의 테이블을 반복적으로 사용가능
SELECT PLAYER_ID , PLAYER_NAME || '(' || BACK_NO || ') ', HEIGHT , HEIGHT FROM PLAYER p ;

SELECT * FROM USER_TAB_PRIVS_MADE; -- SYSTEM 사용자가 부여한 권한
SELECT * FROM USER_TAB_PRIVS_RECD; -- SYSTEM 에게 부여된 권한