SELECT TEAM_ID ,
    COUNT(CASE WHEN "POSITION" = 'DF'THEN "POSITION" END) DF ,
    COUNT(CASE WHEN "POSITION" = 'MF' THEN "POSITION" END) FW, 
    COUNT(CASE WHEN "POSITION" = 'FW' THEN "POSITION" END) GK, 
    COUNT(CASE WHEN "POSITION" = 'GK' THEN "POSITION" END) MF, 
    COUNT(CASE WHEN "POSITION" IS NULL THEN 1 END) 포지션없음,
    COUNT(*) 총인원
FROM PLAYER p 
GROUP BY TEAM_ID ;

 SELECT TEAM_ID ,
 	SUM(CASE WHEN "POSITION" = 'DF' THEN 1 END) DF,
 	SUM(CASE WHEN "POSITION" = 'FW' THEN 1 END) FW,
 	SUM(CASE WHEN "POSITION" = 'GK' THEN 1 END) GK,
 	SUM(CASE WHEN "POSITION" = 'MF' THEN 1 END) MF,
 	SUM(CASE WHEN "POSITION" IS NULL THEN 1 END) 포지션없음,
 	COUNT(*) 총인원
 	FROM PLAYER p 
 	GROUP BY TEAM_ID;

SELECT  TEAM_ID , "POSITION" 
FROM PLAYER p 
WHERE TEAM_ID ='K01';

SELECT TEAM_ID ,
    COUNT(CASE WHEN "POSITION" = 'DF'THEN "POSITION" END) DF ,
    COUNT(CASE WHEN "POSITION" = 'MF' THEN "POSITION" END) FW, 
    COUNT(CASE WHEN "POSITION" = 'FW' THEN "POSITION" END) GK, 
    COUNT(CASE WHEN "POSITION" = 'GK' THEN "POSITION" END) MF, 
    COUNT(CASE WHEN "POSITION" IS NULL THEN 1 END) A,
    COUNT(*) 
FROM PLAYER p 
GROUP BY TEAM_ID ;

SELECT COUNT(*) "전체 행의 수", SUM(SAL) 연봉합계, AVG(SAL) 연봉평균, MAX(SAL) 연봉최댓값, MIN(SAL) 연봉최솟값
	FROM EMP;
	
SELECT EMPNO ,ENAME , TO_CHAR(HIREDATE,'YYYY') 고용일, DNAME 
	FROM EMP e JOIN DEPT d 
	ON e.DEPTNO = d.DEPTNO 
	WHERE JOB='CLERK'