SELECT EMPNO , ENAME 
	FROM EMP e 
	WHERE EMPNO IN('7369','7698');
	
SELECT EMPNO , ENAME 
	FROM EMP e 
	WHERE EMPNO NOT IN('7369','7698');

-- 이상 이하만 됨
SELECT *
	FROM EMP e 
	WHERE SAL BETWEEN '3000' AND '5000';

SELECT *
	FROM EMP e 

SELECT EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO 
	FROM EMP e 
		WHERE HIREDATE > '19811201'; 

--날짜에 관련된 비교 할때는 반드시 크기에 대한 확인
-- 날짜 표기는 .-/  등 통해서 표현히 가능하나 비교할때는 같은 타입
SELECT EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO 
	FROM EMP e 
		WHERE TO_DATE(TO_CHAR(HIREDATE, 'YYYYMMDD')) > TO_DATE('19811201') ; 
	
SELECT MAX(EMPNO)
	FROM EMP e 
		WHERE JOB ='SALESMAN';
--1
SELECT DNAME , EMPNO , ENAME 
	FROM EMP e JOIN DEPT d 
		ON e.DEPTNO = d.DEPTNO 
		ORDER BY DNAME , ENAME ;
	
--2
SELECT DNAME , EMPNO , ENAME 
	FROM EMP e LEFT JOIN DEPT d 
		ON e.DEPTNO = d.DEPTNO
		ORDER BY 1, 3;	
	
SELECT DNAME , EMPNO , ENAME 
	FROM EMP e , DEPT d 
		WHERE e.DEPTNO = d.DEPTNO
		ORDER BY 1, 3;

-- 3
--	3.	부서 위치가 'DALLAS', 'CHICAGO' 곳에 근무하는 사원 정보 아래 
--예제처럼 출력하세요?
--ex) 정렬은 부서위치(LOC) 내림차순, 사원명(ENAME) 오름차순

SELECT LOC, EMPNO , ENAME 
	FROM EMP e JOIN DEPT d 
	ON e.DEPTNO = d.DEPTNO
		WHERE LOC IN('DALLAS', 'CHICAGO')
		ORDER BY LOC DESC, ENAME ; 

SELECT LOC, EMPNO , ENAME
	FROM EMP e JOIN (
				SELECT *
					FROM DEPT d 
						WHERE LOC IN('DALLAS', 'CHICAGO') )d
		ON e.DEPTNO = d.DEPTNO
		ORDER BY LOC DESC, ENAME;

--4
SELECT DEPTNO , MAX(SAL)  
	FROM EMP e 
		GROUP BY DEPTNO  ;	
	
	SELECT DEPTNO , MAX(SAL) SAL
		FROM EMP e 
			WHERE DEPTNO IS NOT NULL 
				GROUP BY DEPTNO 
				ORDER BY DEPTNO;
	
--5
			
SELECT e.DEPTNO , e.SAL , e.EMPNO , JOB 
	FROM  EMP e JOIN(
				SELECT DEPTNO , MAX(SAL) SAL 
				FROM EMP 
				WHERE DEPTNO IS NOT NULL 
				GROUP BY DEPTNO) e2 
			ON e.SAL = e2.SAL 
		ORDER BY DEPTNO;
	
SELECT DEPTNO , SAL , EMPNO , JOB 
	FROM  EMP e NATURAL JOIN(
				SELECT DEPTNO , MAX(SAL) SAL 
				FROM EMP 
				WHERE DEPTNO IS NOT NULL 
				GROUP BY DEPTNO) e2 
		ORDER BY DEPTNO;
	
SELECT SAL 
	FROM EMP e JOIN DEPT d;
	
	
	
	
	