--1
SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH MGR IS NULL 
	CONNECT BY PRIOR EMPNO =  MGR;
	
SELECT *
	FROM EMP e ;

--2
SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH MGR = '7566'
	CONNECT BY PRIOR EMPNO = MGR ;
	
SELECT *
	FROM EMP e ;
	
--3
SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH EMPNO = (SELECT MGR FROM EMP WHERE EMPNO= '7499')
	CONNECT BY  EMPNO = PRIOR MGR ;

--4
SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH EMPNO = '7698' OR EMPNO = '7782'
	CONNECT BY PRIOR EMPNO = MGR ;

--5
SELECT MGR, EMPNO , ENAME , SYS_CONNECT_BY_PATH(ENAME  , '>') RELATION
	FROM EMP e 
	START WITH EMPNO 
	CONNECT BY PRIOR EMPNO = MGR ;
